use_frameworks!

target 'Shimmeraiser_Example' do
  pod 'Shimmeraiser', :path => '../'

   target 'Shimmeraiser_ExampleTests' do
       inherit! :search_paths
       pod 'Nimble', '7.3.0'
       pod 'Quick', '1.3.1'

   end
end
